// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxew7vyGtNojSYlAGLScucy-wLPYBtexI',
    appId: '1:113002158807:web:d902917008d167d7a86e92',
    messagingSenderId: '113002158807',
    projectId: 'todo-list-provider-2dcb9',
    authDomain: 'todo-list-provider-2dcb9.firebaseapp.com',
    storageBucket: 'todo-list-provider-2dcb9.appspot.com',
    measurementId: 'G-F67KD3N8VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNOmYpqIRjlSpVH8WITmHCR5twfnrEh6M',
    appId: '1:113002158807:android:1ef6c7d98790a434a86e92',
    messagingSenderId: '113002158807',
    projectId: 'todo-list-provider-2dcb9',
    storageBucket: 'todo-list-provider-2dcb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYZ-WyK-SIvrlloV6sZ52aPsLK5wKei0',
    appId: '1:113002158807:ios:a4b2c6577881efb1a86e92',
    messagingSenderId: '113002158807',
    projectId: 'todo-list-provider-2dcb9',
    storageBucket: 'todo-list-provider-2dcb9.appspot.com',
    androidClientId: '113002158807-60g0m75k8ccqch62dehi0ag2m19068vp.apps.googleusercontent.com',
    iosClientId: '113002158807-brde6o19ilf1ggjmi31i95e6a710n59q.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYZ-WyK-SIvrlloV6sZ52aPsLK5wKei0',
    appId: '1:113002158807:ios:a4b2c6577881efb1a86e92',
    messagingSenderId: '113002158807',
    projectId: 'todo-list-provider-2dcb9',
    storageBucket: 'todo-list-provider-2dcb9.appspot.com',
    androidClientId: '113002158807-60g0m75k8ccqch62dehi0ag2m19068vp.apps.googleusercontent.com',
    iosClientId: '113002158807-brde6o19ilf1ggjmi31i95e6a710n59q.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );
}
